apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garmin-kibana
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: garmin-kibana-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication required - Garmin Kibana"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: kibana-garmin.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garmin-kibana
                port: {name: http}
