apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpixel
  namespace: workloads
spec:
  ingressClassName: nginx
  rules:
    - host: webpixel.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpixel
                port:
                  number: 80
